############################################
# LEIA AQUI                                
############################################
# Criado por GUILHERME LAZAROTTO           
# Youtube: www.youtube.com/@guilherme_laz  
# Curso completo: www.curson8n.com.br      
############################################

services:
  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"


volumes:
  pgdata:
  waha_sessions:
  waha_media:
  n8n_data:
